// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AniLoader: typeof import('./src/components/img/aniLoader.vue')['default']
    AppAlert: typeof import('./src/components/ui/AppAlert.vue')['default']
    AppButton: typeof import('./src/components/form/AppButton.vue')['default']
    AppCard: typeof import('./src/components/form/AppCard.vue')['default']
    AppContainer: typeof import('./src/components/layout/content/AppContainer.vue')['default']
    AppFeedItem: typeof import('./src/components/lists/feed/AppFeedItem.vue')['default']
    AppFeedList: typeof import('./src/components/lists/feed/AppFeedList.vue')['default']
    AppFileInput: typeof import('./src/components/form/AppFileInput.vue')['default']
    AppGallery: typeof import('./src/components/lists/gallery/AppGallery.vue')['default']
    AppGalleryItem: typeof import('./src/components/lists/gallery/AppGalleryItem.vue')['default']
    AppGrid: typeof import('./src/components/layout/content/AppGrid.vue')['default']
    AppHeading: typeof import('./src/components/text/AppHeading.vue')['default']
    AppHero: typeof import('./src/components/ui/AppHero.vue')['default']
    AppImage: typeof import('./src/components/ui/AppImage.vue')['default']
    AppIngredientItem: typeof import('./src/components/lists/ingredients/AppIngredientItem.vue')['default']
    AppIngredientList: typeof import('./src/components/lists/ingredients/AppIngredientList.vue')['default']
    AppInput: typeof import('./src/components/form/AppInput.vue')['default']
    AppNavbar: typeof import('./src/components/layout/navbar/AppNavbar.vue')['default']
    AppNavbarItem: typeof import('./src/components/layout/navbar/AppNavbarItem.vue')['default']
    AppPill: typeof import('./src/components/lists/pills/AppPill.vue')['default']
    AppPillList: typeof import('./src/components/lists/pills/AppPillList.vue')['default']
    AppScreenModal: typeof import('./src/components/layout/AppScreenModal.vue')['default']
    AppSearch: typeof import('./src/components/ui/AppSearch.vue')['default']
    AppSelect: typeof import('./src/components/form/AppSelect.vue')['default']
    AppSidebar: typeof import('./src/components/layout/navbar/AppSidebar.vue')['default']
    AppSwitch: typeof import('./src/components/form/AppSwitch.vue')['default']
    AppTextArea: typeof import('./src/components/form/AppTextArea.vue')['default']
    IClose: typeof import('./src/components/icons/iClose.vue')['default']
    ILock: typeof import('./src/components/icons/iLock.vue')['default']
    ILogin: typeof import('./src/components/icons/iLogin.vue')['default']
    IMail: typeof import('./src/components/icons/iMail.vue')['default']
    IMenu: typeof import('./src/components/icons/iMenu.vue')['default']
    ImgCookingHero: typeof import('./src/components/img/imgCookingHero.vue')['default']
    ImgCookingManagement: typeof import('./src/components/img/imgCookingManagement.vue')['default']
    ImgUpload: typeof import('./src/components/img/imgUpload.vue')['default']
    INewUser: typeof import('./src/components/icons/iNewUser.vue')['default']
    ISearch: typeof import('./src/components/icons/iSearch.vue')['default']
    IUser: typeof import('./src/components/icons/iUser.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgCookingHero: typeof import('./src/components/svg/svgCookingHero.vue')['default']
    SvgCookingManagement: typeof import('./src/components/svg/svgCookingManagement.vue')['default']
    SvgLoader: typeof import('./src/components/svg/svgLoader.vue')['default']
    SvgUpload: typeof import('./src/components/svg/svgUpload.vue')['default']
  }
}

export {}
