// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/widgets/AppAlert.vue')['default']
    AppButton: typeof import('./src/components/form/AppButton.vue')['default']
    AppCalenderItem: typeof import('./src/components/calendar/AppCalenderItem.vue')['default'];
    AppCalenderWeek: typeof import('./src/components/diet-planner/AppCalenderWeek.vue')['default'];
    'AppCalenderWeek copy': typeof import('./src/components/calendar/AppCalenderWeek copy.vue')['default'];
    AppCard: typeof import('./src/components/form/AppCard.vue')['default']
    AppContainer: typeof import('./src/components/layout/content/AppContainer.vue')['default']
    AppDietCalender: typeof import('./src/components/diet-planner/AppDietCalender.vue')['default'];
    AppDietDay: typeof import('./src/components/diet-planner/AppDietDay.vue')['default'];
    AppDietForm: typeof import('./src/components/diet-planner/AppDietForm.vue')['default'];
    AppDietLegend: typeof import('./src/components/diet-planner/AppDietLegend.vue')['default'];
    AppDietMonth: typeof import('./src/components/widgets/diet-planner/AppDietMonth.vue')['default']
    AppDietPlanner: typeof import('./src/components/diet-planner/AppDietPlanner.vue')['default'];
    AppDietRow: typeof import('./src/components/widgets/diet-planner/AppDietRow.vue')['default']
    AppDietWeek: typeof import('./src/components/widgets/diet-planner/AppDietWeek.vue')['default']
    AppFeed: typeof import('./src/components/lists/feed/AppFeed.vue')['default']
    AppFeedItem: typeof import('./src/components/lists/feed/AppFeedItem.vue')['default']
    AppFileInput: typeof import('./src/components/form/AppFileInput.vue')['default']
    AppGallery: typeof import('./src/components/lists/gallery/AppGallery.vue')['default']
    AppGalleryCard: typeof import('./src/components/lists/gallery/AppGalleryCard.vue')['default'];
    AppGalleryItem: typeof import('./src/components/lists/gallery/AppGalleryItem.vue')['default']
    AppGalleryRecipeCard: typeof import('./src/components/lists/gallery/AppGalleryRecipeCard.vue')['default']
    AppGrid: typeof import('./src/components/layout/content/AppGrid.vue')['default']
    AppHero: typeof import('./src/components/layout/content/AppHero.vue')['default']
    AppImage: typeof import('./src/components/ui/AppImage.vue')['default']
    AppIngredientItem: typeof import('./src/components/lists/ingredients/AppIngredientItem.vue')['default']
    AppIngredientList: typeof import('./src/components/lists/ingredients/AppIngredientList.vue')['default']
    AppInput: typeof import('./src/components/form/AppInput.vue')['default']
    AppMarkdown: typeof import('./src/components/widgets/AppMarkdown.vue')['default']
    AppNavbar: typeof import('./src/components/layout/navbar/AppNavbar.vue')['default']
    AppNavbarItem: typeof import('./src/components/layout/navbar/AppNavbarItem.vue')['default']
    AppNavbarSearch: typeof import('./src/components/layout/navbar/AppNavbarSearch.vue')['default']
    AppPill: typeof import('./src/components/lists/pills/AppPill.vue')['default']
    AppPillList: typeof import('./src/components/lists/pills/AppPillList.vue')['default']
    AppProfileHeader: typeof import('./src/components/public-user/AppProfileHeader.vue')['default']
    AppRecipeTile: typeof import('./src/components/widgets/tiles/AppRecipeTile.vue')['default'];
    AppRouterLink: typeof import('./src/components/layout/navbar/AppRouterLink.vue')['default']
    AppScreenModal: typeof import('./src/components/ui/AppScreenModal.vue')['default']
    AppSearch: typeof import('./src/components/widgets/AppSearch.vue')['default']
    AppSelect: typeof import('./src/components/form/AppSelect.vue')['default']
    AppSidebar: typeof import('./src/components/layout/navbar/AppSidebar.vue')['default']
    AppSocialBar: typeof import('./src/components/public-user/AppSocialBar.vue')['default']
    AppSwitch: typeof import('./src/components/form/AppSwitch.vue')['default']
    AppTag: typeof import('./src/components/lists/pills/AppTag.vue')['default']
    AppTextArea: typeof import('./src/components/form/AppTextArea.vue')['default']
    AppTile: typeof import('./src/components/ui/AppTile.vue')['default']
    AppTiles: typeof import('./src/components/widgets/AppTiles.vue')['default'];
    AppToolbar: typeof import('./src/components/layout/toolbar/AppToolbar.vue')['default']
    DietPlanner: typeof import('./src/components/diet-planner/index.vue')['default'];
    IChart: typeof import('./src/components/icons/iChart.vue')['default']
    IClock: typeof import('./src/components/icons/iClock.vue')['default']
    IClose: typeof import('./src/components/icons/iClose.vue')['default']
    IFacebook: typeof import('./src/components/icons/brands/iFacebook.vue')['default']
    IFire: typeof import('./src/components/icons/iFire.vue')['default']
    IInstagram: typeof import('./src/components/icons/brands/iInstagram.vue')['default']
    ILock: typeof import('./src/components/icons/iLock.vue')['default']
    ILogin: typeof import('./src/components/icons/iLogin.vue')['default']
    IMail: typeof import('./src/components/icons/iMail.vue')['default']
    IMenu: typeof import('./src/components/icons/iMenu.vue')['default']
    INewUser: typeof import('./src/components/icons/iNewUser.vue')['default']
    IPinterest: typeof import('./src/components/icons/brands/iPinterest.vue')['default']
    ISearch: typeof import('./src/components/icons/iSearch.vue')['default']
    IShoppingBag: typeof import('./src/components/icons/iShoppingBag.vue')['default']
    IUser: typeof import('./src/components/icons/iUser.vue')['default']
    IVdcLogo: typeof import('./src/components/icons/brands/iVdcLogo.vue')['default']
    IVdcLogoDark: typeof import('./src/components/icons/brands/iVdcLogoDark.vue')['default']
    KitchenTiles: typeof import('./src/components/widgets/KitchenTiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgCookingHero: typeof import('./src/components/icons/svg/svgCookingHero.vue')['default']
    SvgCookingManagement: typeof import('./src/components/icons/svg/svgCookingManagement.vue')['default']
    SvgLoader: typeof import('./src/components/icons/svg/svgLoader.vue')['default']
    SvgUpload: typeof import('./src/components/icons/svg/svgUpload.vue')['default']
  }
}

export {}
