version: '3.8' # Version of docker-compose spec
services: # An object that specifies the containers that are used
  frontend:
    build:
      context: ./frontend
      dockerfile: fe.dev.dockerfile

    # volumes are only relevant for development
    volumes:
      - ./frontend:/frontend

    ports:
      - '3000:3000'
    expose:
      - '3000'
    stdin_open: true
    tty: true